# labels are key value pairs used for filtering the images, in dockerfile of docker labels are optional but in kubernetes pods labels are mandatory
kind: Pod
apiVersion: v1
metadata:
  name: labels
  labels:
    project: expense
    module: backend
    environment: dev
spec:
  containers:
  - name: nginx
    image: nginx
