apiVersion: v1
kind: Pod
metadata:
  name: annotations
  annotations:
    project: expense
    component: mysql
    tier: backend
    environment: dev
  annotations:
    description: "This pod is created to demonstrate pod annotations"
    buildURL: "https://jenkins.com/build/job/roboshop-catalouge/3"
spec:
  containers:
  - name: nginx
    image: nginx